/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nz.ac.aut.ense701.gui;

import java.awt.Font;

/**
 *
 */
public class Description extends javax.swing.JPanel {
    
    MainFrame main;
    
    /** Creates new form Description */
    public Description(MainFrame frame) {
        this.main = frame;
        this.setBounds(0, 0, 600, 410);
        initComponents();
        
        desText.setFont(new Font("Arial", Font.BOLD, 15));
        desText.setText("<html>Unicorn Island consists of many mystical creatures such as;"
                + "<br>Fairies, Pegasus, Mermaids, Griffins, Pixies, and more."
                + "<br>For many years, the Unicorns have been huntered by many"
                + "<br>preditors and forcing them into hiding. Your quest as "
                + "<br>an adventurer is to find and trap these predators to"
                + "<br>bring back peace to Unicorn Island."
                + "<br>Good Luck Adventurer!</html>");
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desText = new javax.swing.JLabel();
        descHead = new javax.swing.JLabel();
        backBut = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desText.setText("Text");
        add(desText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        descHead.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        descHead.setText("Description");
        add(descHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 310, 40));

        backBut.setText("Back");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background2_1.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        // TODO add your handling code here:
        main.remove(this);
        main.add(main.menu);
        main.panelRedraw();
    }//GEN-LAST:event_backButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JLabel background;
    private javax.swing.JLabel desText;
    private javax.swing.JLabel descHead;
    // End of variables declaration//GEN-END:variables

}
