/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import Records.GamePlayerRecord;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Bonaliza
 */
public class MainFrame extends javax.swing.JFrame {

    Game game;
    Menu menu;
    Profile profile;
    HighScore hscore;
    Description desc;
    GamePlayerRecord playerRecord;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        game = new Game();
        playerRecord = new GamePlayerRecord();
        menu = new Menu(this);
        profile = new Profile(this);
        hscore = new HighScore(this);
        desc = new Description(this);
        
        initComponents();
        
        this.setBounds(0, 0, 600, 440);
        this.setLocationRelativeTo(null);
        this.add(menu);
        panelRedraw();
    }

    public final void panelRedraw()
    {
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unicorn Island");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
