/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Bonaliza
 */
public class Menu extends javax.swing.JPanel {

    MainFrame main;
    boolean startGame = false;
    
    /**
     * Creates new form Menu
     */
    public Menu(MainFrame frame) {
        this.main = frame;
        this.setBounds(0, 0, 600, 410);
        initComponents();
        
        //ImageIcone playImage = new ImageIcon("")
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBut = new javax.swing.JButton();
        profBut = new javax.swing.JButton();
        hscoreBut = new javax.swing.JButton();
        descBut = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playBut.setText("Play");
        playBut.setPreferredSize(new java.awt.Dimension(55, 25));
        playBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButActionPerformed(evt);
            }
        });
        add(playBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, -1));

        profBut.setText("My Profile");
        profBut.setPreferredSize(new java.awt.Dimension(80, 25));
        profBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profButActionPerformed(evt);
            }
        });
        add(profBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 100, -1));

        hscoreBut.setText("HighScore");
        hscoreBut.setPreferredSize(new java.awt.Dimension(80, 25));
        hscoreBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hscoreButActionPerformed(evt);
            }
        });
        add(hscoreBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 100, -1));

        descBut.setText("Description");
        descBut.setPreferredSize(new java.awt.Dimension(85, 25));
        descBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descButActionPerformed(evt);
            }
        });
        add(descBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 100, -1));

        exitBut.setText("Quit");
        exitBut.setPreferredSize(new java.awt.Dimension(50, 25));
        exitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButActionPerformed(evt);
            }
        });
        add(exitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 60, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background2.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void hscoreButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hscoreButActionPerformed
        main.remove(this);
        main.add(main.hscore);
        main.panelRedraw();
    }//GEN-LAST:event_hscoreButActionPerformed

    private void exitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButActionPerformed

    private void profButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profButActionPerformed
        main.remove(this);
        main.add(main.profile);
        main.panelRedraw();
    }//GEN-LAST:event_profButActionPerformed

    private void descButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descButActionPerformed
        main.remove(this);
        main.add(main.desc);
        main.panelRedraw();
    }//GEN-LAST:event_descButActionPerformed

    private void playButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButActionPerformed
        if(startGame == false){
            // create the game object
            final Game game = new Game();
            // create the GUI for the game
            final KiwiCountUI  gui  = new KiwiCountUI(game);
            // make the GUI visible
            java.awt.EventQueue.invokeLater(new Runnable() 
            {
                @Override
                public void run() 
                {
                    gui.setVisible(true);
                }
            });
            startGame = true;
        }else{
            JOptionPane.showMessageDialog(null, "Game has already started", "Alert!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_playButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton descBut;
    private javax.swing.JButton exitBut;
    private javax.swing.JButton hscoreBut;
    private javax.swing.JButton playBut;
    private javax.swing.JButton profBut;
    // End of variables declaration//GEN-END:variables
}
